version: "3.8"

services:

  web:
    build: ./encurtador-web  
    volumes:
      - ./encurtador-web:/app
      - /app/node_modules
      - ./.vite:/app/.vite
    ports:
      - "5173:5173"
    environment:
      - VITE_LIVERELOAD=true
      - VITE_LIVERELOAD_PORT=35729

  api:
    build:
      context: ./encurtador-api
      dockerfile: Dockerfile
    volumes:
      - ./encurtador-api/:/var/www

  nginx:
    image: nginx:alpine
    ports:
      - "8989:80"
    volumes:
      - ./encurtador-api:/var/www
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf

  cron:
    build:
      context: ./encurtador-api
      dockerfile: cron.dockerfile
    container_name: cron
    volumes:
      - ./encurtador-api:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: encurtador
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
